/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Stadium, Gate, Concession, Volunteer, TransitRoute, Incident } from "./types";

export const STADIUMS: Stadium[] = [
  {
    id: "metlife",
    name: "MetLife Stadium (New York New Jersey)",
    city: "East Rutherford",
    country: "USA",
    capacity: 82500,
    featuredMatch: {
      home: "Argentina",
      away: "France",
      time: "19:00 local time",
      stage: "FIFA World Cup Final 2026",
    },
  },
  {
    id: "azteca",
    name: "Estadio Azteca",
    city: "Mexico City",
    country: "Mexico",
    capacity: 87523,
    featuredMatch: {
      home: "Mexico",
      away: "Italy",
      time: "18:00 local time",
      stage: "Opening Match - Group Stage",
    },
  },
  {
    id: "bcplace",
    name: "BC Place Stadium",
    city: "Vancouver",
    country: "Canada",
    capacity: 54500,
    featuredMatch: {
      home: "Canada",
      away: "England",
      time: "17:00 local time",
      stage: "Round of 16",
    },
  },
];

export const INITIAL_GATES: Record<string, Gate[]> = {
  metlife: [
    { name: "Gate A (Bud Light Gate)", status: "Open", waitMinutes: 8, congestion: "Low" },
    { name: "Gate B (Verizon Gate)", status: "Slow", waitMinutes: 24, congestion: "High" },
    { name: "Gate C (Pepsi Gate)", status: "Open", waitMinutes: 12, congestion: "Medium" },
    { name: "Gate D (HCL Tech Gate)", status: "Closed", waitMinutes: 0, congestion: "Low" },
  ],
  azteca: [
    { name: "Acceso Principal (Gate 1)", status: "Slow", waitMinutes: 35, congestion: "High" },
    { name: "Acceso Norte (Gate 2)", status: "Open", waitMinutes: 10, congestion: "Low" },
    { name: "Acceso Oriente (Gate 3)", status: "Open", waitMinutes: 15, congestion: "Medium" },
    { name: "Acceso Sur (Gate 4)", status: "Open", waitMinutes: 5, congestion: "Low" },
  ],
  bcplace: [
    { name: "Gate A (Robson St)", status: "Open", waitMinutes: 5, congestion: "Low" },
    { name: "Gate C (Pacific Blvd)", status: "Slow", waitMinutes: 18, congestion: "High" },
    { name: "Gate E (Beatty St)", status: "Open", waitMinutes: 10, congestion: "Medium" },
    { name: "Gate H (Terry Fox)", status: "Open", waitMinutes: 4, congestion: "Low" },
  ],
};

export const INITIAL_CONCESSIONS: Record<string, Concession[]> = {
  metlife: [
    {
      id: "ml-c1",
      name: "Tacos & Micheladas 2026",
      location: "Section 114 (Concourse Level 1)",
      category: "Food",
      specialty: ["Mexican", "Gluten-Free Available", "Spicy Foods"],
      isAccessible: true,
      waitMinutes: 12,
      congestion: "Medium",
    },
    {
      id: "ml-c2",
      name: "Jersey Burger Grill",
      location: "Section 142 (Concourse Level 1)",
      category: "Food",
      specialty: ["American Burgers", "Halal Options", "Vegetarian Burgers"],
      isAccessible: true,
      waitMinutes: 22,
      congestion: "High",
    },
    {
      id: "ml-c3",
      name: "Green Fields Sustainability Bowls",
      location: "Section 212 (Concourse Level 2)",
      category: "Food",
      specialty: ["Vegan Bowls", "Eco-friendly compostable packaging", "Organic"],
      isAccessible: true,
      waitMinutes: 4,
      congestion: "Low",
    },
    {
      id: "ml-c4",
      name: "hydration Oasis",
      location: "Section 118",
      category: "Water Station",
      specialty: ["Free Pure Filtered Water", "Bring-your-own-cup friendly"],
      isAccessible: true,
      waitMinutes: 1,
      congestion: "Low",
    },
    {
      id: "ml-c5",
      name: "FIFA Fan Shop & Merchandise",
      location: "Section 104 (Plaza Level)",
      category: "Merchandise",
      specialty: ["World Cup Kits", "Caps", "Accessible service counters"],
      isAccessible: true,
      waitMinutes: 18,
      congestion: "High",
    },
    {
      id: "ml-c6",
      name: "First Aid & Accessibility Hub",
      location: "Section 128 (Concourse Level 1)",
      category: "First Aid",
      specialty: ["Medical Care", "Wheelchair Rentals", "Sensory Bags Available"],
      isAccessible: true,
      waitMinutes: 0,
      congestion: "Low",
    },
  ],
  azteca: [
    {
      id: "az-c1",
      name: "Gorditas y Quesadillas El Estadio",
      location: "Túnel 8",
      category: "Food",
      specialty: ["Traditional Mexican", "Vegetarian options"],
      isAccessible: false,
      waitMinutes: 25,
      congestion: "High",
    },
    {
      id: "az-c2",
      name: "Estadio Brews",
      location: "Sección 120",
      category: "Beverages",
      specialty: ["Local Mexican Beers", "Micheladas", "Sodas"],
      isAccessible: true,
      waitMinutes: 15,
      congestion: "Medium",
    },
    {
      id: "az-c3",
      name: "Estación de Hidratación Gratuita",
      location: "Sección 105",
      category: "Water Station",
      specialty: ["Free Water Refills", "Eco-sustainable cups"],
      isAccessible: true,
      waitMinutes: 2,
      congestion: "Low",
    },
    {
      id: "az-c4",
      name: "Tienda Oficial FIFA",
      location: "Acceso Principal",
      category: "Merchandise",
      specialty: ["Jerseys", "Souvenirs"],
      isAccessible: true,
      waitMinutes: 20,
      congestion: "High",
    },
  ],
  bcplace: [
    {
      id: "bc-c1",
      name: "Pacific Salmon & Seafood Co.",
      location: "Section 218",
      category: "Food",
      specialty: ["B.C. Wild Salmon Burgers", "Gluten-Free"],
      isAccessible: true,
      waitMinutes: 10,
      congestion: "Medium",
    },
    {
      id: "bc-c2",
      name: "Poutine Nation",
      location: "Section 244",
      category: "Food",
      specialty: ["Canadian Poutine", "Vegan Gravy available"],
      isAccessible: true,
      waitMinutes: 18,
      congestion: "High",
    },
    {
      id: "bc-c3",
      name: "Eco-Bites Veggie Hub",
      location: "Section 208",
      category: "Food",
      specialty: ["Organic Salads", "Compostable serving wares"],
      isAccessible: true,
      waitMinutes: 3,
      congestion: "Low",
    },
    {
      id: "bc-c4",
      name: "Cascade Water Station",
      location: "Section 222",
      category: "Water Station",
      specialty: ["Chilled Glacier Water Refills"],
      isAccessible: true,
      waitMinutes: 2,
      congestion: "Low",
    },
  ],
};

export const INITIAL_VOLUNTEERS: Volunteer[] = [
  {
    id: "v1",
    name: "Mateo Silva",
    status: "Available",
    location: "Gate B (Verizon Gate)",
    languages: ["Spanish", "English", "Portuguese"],
    skills: ["First Aid", "Stadium Layout Navigation", "Wheelchair Escort"],
  },
  {
    id: "v2",
    name: "Yuki Tanaka",
    status: "On Task",
    location: "Concourse Section 120",
    languages: ["Japanese", "English"],
    skills: ["Language Interpretation", "Lost & Found Logistics"],
  },
  {
    id: "v3",
    name: "Amina Al-Sayed",
    status: "Available",
    location: "Plaza Level / Gate C",
    languages: ["Arabic", "English", "French"],
    skills: ["De-escalation", "Crowd Control Guidance", "First Aid"],
  },
  {
    id: "v4",
    name: "Jean-Pierre Laurent",
    status: "Available",
    location: "Gate A Entrance",
    languages: ["French", "English", "German"],
    skills: ["Accessibility Coordination", "Elderly Assistance"],
  },
  {
    id: "v5",
    name: "Elena Rostova",
    status: "Off Duty",
    location: "Staff Lounge",
    languages: ["Russian", "English"],
    skills: ["Ticketing Troubleshooting", "VIP Concierge"],
  },
];

export const INITIAL_TRANSIT: TransitRoute[] = [
  {
    id: "t1",
    mode: "Train",
    name: "Meadowlands Express Rail Link",
    frequencyMinutes: 6,
    status: "On Time",
    delayMinutes: 0,
    sustainabilityRating: "A",
  },
  {
    id: "t2",
    mode: "Shuttle",
    name: "MetLife Eco-Hybrid Park & Ride Bus",
    frequencyMinutes: 10,
    status: "Delayed",
    delayMinutes: 12,
    sustainabilityRating: "B",
  },
  {
    id: "t3",
    mode: "Ride Share",
    name: "Ride-Share Pick-up Zone (Lot E)",
    frequencyMinutes: 2,
    status: "Crowded",
    delayMinutes: 25,
    sustainabilityRating: "D",
  },
  {
    id: "t4",
    mode: "Walking",
    name: "Hackensack Pedestrian Green Way",
    frequencyMinutes: 1,
    status: "On Time",
    delayMinutes: 0,
    sustainabilityRating: "A",
  },
];

export const INITIAL_INCIDENTS: Incident[] = [
  {
    id: "inc-101",
    description: "Liquid spill of soda creates slipping hazard on stairs near Concourse Section 114.",
    location: "Concourse Section 114 Stairs",
    category: "Facility",
    severity: "Medium",
    reportedAt: "09:12 AM",
    status: "Reported",
    aiDispatchRecommendation: "Dispatch a facility service worker immediately. Notify nearest Volunteer Amina Al-Sayed to tape off area temporarily.",
  },
  {
    id: "inc-102",
    description: "Elderly fan in seat 14-D row M feels lightheaded and needs a wheelchair escort to Section 128 Medical Station.",
    location: "Section 142, Row M, Seat 14-D",
    category: "Medical",
    severity: "Critical",
    reportedAt: "09:18 AM",
    status: "Dispatched",
    assignedVolunteerId: "v1",
    assignedVolunteerName: "Mateo Silva",
    aiDispatchRecommendation: "CRITICAL: Priority Medical Call. Assigned Volunteer Mateo Silva (First Aid & Wheelchair Escort skilled) is responding from Gate B with a medical kit and backup chair.",
  },
  {
    id: "inc-103",
    description: "Visitor cannot find lost passport which was left near the FIFA Fan Shop.",
    location: "Plaza Level Fan Shop",
    category: "Lost & Found",
    severity: "Low",
    reportedAt: "09:20 AM",
    status: "Reported",
    aiDispatchRecommendation: "Recommend directing user to standard lost-and-found repository. Alert nearest available volunteer Yuki Tanaka on Lost & Found logistics.",
  },
];
